version: "3.8"

services:
  web:
    build: .
    command: gunicorn myagkoe_mesto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
      - backend_static:/usr/src/backend/backend_static
      - backend_media:/usr/src/backend/backend_media
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - backend_static:/usr/src/backend/backend_static
      - backend_media:/usr/src/backend/backend_media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  backend_static:
  backend_media: