version: "3.8"

services:
  web:
    build: .
    volumes:
      - /etc/letsencrypt/live/mebelnyibutikmm.ru/:/etc/letsencrypt/live/mebelnyibutikmm.ru/
      - /etc/letsencrypt/live/xn--90aakbqejefiag1en1joa.xn--p1ai/:/etc/letsencrypt/live/xn--90aakbqejefiag1en1joa.xn--p1ai/
      - /etc/letsencrypt/live/mebelnyibutikmm.store/:/etc/letsencrypt/live/mebelnyibutikmm.store/
      - static_volume:/home/online_store/backend/backend_static
      - media_volume:/home/online_store/backend/backend_media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/home/online_store/backend/backend_static
      - media_volume:/home/online_store/backend/backend_media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: