version: "3.8"

services:
  web:
    build: .
    volumes:
      - static_volume:/home/online_store/backend/backend_static
      - media_volume:/home/online_store/backend/backend_media
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/online_store/backend/backend_static
      - media_volume:/home/online_store/backend/backend_media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: