# Generated by Django 4.2.3 on 2023-07-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('name',), 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
    ]
