# Generated by Django 4.2.4 on 2023-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Введите Производителя', max_length=250, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='model',
            field=models.CharField(blank=True, help_text='Введите тип товара', max_length=250, verbose_name='Тип модели'),
        ),
    ]
