# Generated by Django 4.2.4 on 2023-08-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Введите тег', max_length=250, unique=True, verbose_name='Название ц')),
                ('hex', models.CharField(help_text='Укажите цвет тега', max_length=7, unique=True, verbose_name='Код цвета')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Слаг цвета')),
            ],
            options={
                'verbose_name': 'Тег цвета',
                'verbose_name_plural': 'Теги цвета',
            },
        ),
        migrations.RemoveField(
            model_name='variationproduct',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variationproduct',
            name='size',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='color_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.colortag', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='products.category', verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='specification',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_in_specific', to='products.size', verbose_name='Размер товара'),
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.size', verbose_name='Размер товара'),
        ),
    ]
