# Generated by Django 4.2.3 on 2023-07-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_basket_product_alter_favorite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фото товара', upload_to='product/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationproduct')),
            ],
        ),
    ]
