# Generated by Django 4.2.4 on 2023-08-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colortag_remove_variationproduct_tags_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colortag',
            old_name='color',
            new_name='color_name',
        ),
    ]
