# Generated by Django 4.2.4 on 2023-09-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(help_text='Загрузите фото товара', null=True, upload_to='product/%Y/%m/%d', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.picture', verbose_name='Картинка типа товара'),
        ),
    ]
