# Generated by Django 4.2.4 on 2023-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_color_colortag_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortag',
            name='color_name',
            field=models.CharField(help_text='Введите тег', max_length=250, unique=True, verbose_name='Название цвета'),
        ),
    ]
