# Generated by Django 4.2.3 on 2023-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_image_options_remove_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, help_text='Напишите описание товара', verbose_name='Описание товара'),
        ),
        migrations.RemoveField(
            model_name='variationproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='image',
            field=models.ManyToManyField(related_name='pictures', to='products.image', verbose_name='Фотографии'),
        ),
    ]
