# Generated by Django 4.2.4 on 2023-08-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('products', '0005_alter_colortag_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(blank=True, default=0, verbose_name='Общее количество')),
                ('total_price', models.IntegerField(blank=True, default=0, verbose_name='Общая цена')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='client.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ordercart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationproduct', verbose_name='Продукт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variationproduct', verbose_name='Продукт'),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
