# Generated by Django 4.2.4 on 2023-08-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_ordercart_orderproduct_alter_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='total_quantity',
        ),
    ]
