# Generated by Django 4.2.3 on 2023-07-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_text_remove_variationproduct_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фото товара', upload_to='product/%Y/%m/%d', verbose_name='Фото товара')),
            ],
        ),
        migrations.RemoveField(
            model_name='variationproduct',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variation_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variationproduct', verbose_name='Товар с вариациями'),
        ),
    ]
