# Generated by Django 4.2.3 on 2023-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_image_delete_productimage_variationproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='image',
            field=models.ManyToManyField(related_name='pictures', to='products.image', verbose_name='Фотографии'),
        ),
    ]
