# Generated by Django 4.2.3 on 2023-07-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_variationproduct_image_variationproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='type',
            field=models.CharField(default=1, help_text='Введите материлы товара', max_length=200, verbose_name='Материлы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationproduct',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Цена после скидки'),
            preserve_default=False,
        ),
    ]
