# Generated by Django 4.2.3 on 2023-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_specification_type_variationproduct_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationproduct',
            name='price_2',
        ),
        migrations.AlterField(
            model_name='specification',
            name='article_number',
            field=models.CharField(blank=True, help_text='Введите артикул товара', max_length=200, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='manufacturer',
            field=models.CharField(help_text='Введите Производителя', max_length=200, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='type',
            field=models.CharField(help_text='Введите тип товараНапример угловой', max_length=200, verbose_name='Тип механизмов'),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='products.size', verbose_name='Размер товара'),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='colour', to='products.tag', verbose_name='Цвет товара'),
        ),
    ]
