# Generated by Django 4.2.4 on 2023-08-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_variationproduct_price_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='type',
            field=models.CharField(help_text='Введите тип товара', max_length=200, verbose_name='Тип механизмов'),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='image',
            field=models.ManyToManyField(to='products.image', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='variationproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product', verbose_name='Товары'),
        ),
    ]
