# Generated by Django 4.2.4 on 2023-08-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_specification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='type',
            new_name='mechanism',
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='высота'),
        ),
    ]
