# Generated by Django 4.2.4 on 2023-08-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_type_specification_mechanism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='mechanism',
        ),
        migrations.AddField(
            model_name='specification',
            name='model',
            field=models.CharField(default=0, help_text='Введите тип товара', max_length=200, verbose_name='Тип модели'),
            preserve_default=False,
        ),
    ]
