# Generated by Django 4.2.4 on 2023-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_specification_mechanism_specification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='model',
            field=models.CharField(help_text='Введите тип товара', max_length=200, verbose_name='Тип механизмов'),
        ),
    ]
