# Generated by Django 4.2.4 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_basket_user_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationproduct',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
