# Generated by Django 4.2.4 on 2023-08-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_variationproduct_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationproduct',
            name='pub_date',
        ),
    ]
