# Generated by Django 4.2.4 on 2023-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_basket'),
        ),
    ]
