# Generated by Django 4.2.4 on 2023-08-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.AlterModelOptions(
            name='ordercart',
            options={'verbose_name': 'Корзина в заказе пользователя', 'verbose_name_plural': 'Корзины в заказе пользователя'},
        ),
    ]
