# Generated by Django 4.2.4 on 2023-08-18 08:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backcall',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=20, region='RU', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Введите номер телефона', max_length=20, region='RU', verbose_name='Телефон'),
        ),
    ]
