openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/categories/:
    get:
      operationId: listCategorys
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
      tags:
      - api
  /api/categories/{id}/:
    get:
      operationId: retrieveCategory
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041A\u0430\u0442\u0435\
          \u0433\u043E\u0440\u0438\u044F."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
      tags:
      - api
  /api/type/:
    get:
      operationId: listTypes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Type'
          description: ''
      tags:
      - api
  /api/type/{id}/:
    get:
      operationId: retrieveType
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0422\u0438\u043F."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
      tags:
      - api
  /api/tags/:
    get:
      operationId: listTags
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
          description: ''
      tags:
      - api
  /api/tags/{id}/:
    get:
      operationId: retrieveTag
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0422\u0435\u0433."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
      tags:
      - api
  /api/size/:
    get:
      operationId: listSizes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Size'
          description: ''
      tags:
      - api
  /api/size/{id}/:
    get:
      operationId: retrieveSize
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0420\u0430\u0437\u043C\
          \u0435\u0440."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Size'
          description: ''
      tags:
      - api
  /api/product/:
    get:
      operationId: listVariationProducts
      description: ''
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: tags
        required: false
        in: query
        description: tags
        schema:
          type: string
      - name: size
        required: false
        in: query
        description: size
        schema:
          type: string
      - name: model
        required: false
        in: query
        description: model
        schema:
          type: string
      - name: min_price
        required: false
        in: query
        description: min_price
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: max_price
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    post:
      operationId: createVariationProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
  /api/product/{id}/:
    get:
      operationId: retrieveVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      - name: tags
        required: false
        in: query
        description: tags
        schema:
          type: string
      - name: size
        required: false
        in: query
        description: size
        schema:
          type: string
      - name: model
        required: false
        in: query
        description: model
        schema:
          type: string
      - name: min_price
        required: false
        in: query
        description: min_price
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: max_price
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    put:
      operationId: updateVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      - name: tags
        required: false
        in: query
        description: tags
        schema:
          type: string
      - name: size
        required: false
        in: query
        description: size
        schema:
          type: string
      - name: model
        required: false
        in: query
        description: model
        schema:
          type: string
      - name: min_price
        required: false
        in: query
        description: min_price
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: max_price
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      - name: tags
        required: false
        in: query
        description: tags
        schema:
          type: string
      - name: size
        required: false
        in: query
        description: size
        schema:
          type: string
      - name: model
        required: false
        in: query
        description: model
        schema:
          type: string
      - name: min_price
        required: false
        in: query
        description: min_price
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: max_price
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      - name: tags
        required: false
        in: query
        description: tags
        schema:
          type: string
      - name: size
        required: false
        in: query
        description: size
        schema:
          type: string
      - name: model
        required: false
        in: query
        description: model
        schema:
          type: string
      - name: min_price
        required: false
        in: query
        description: min_price
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: max_price
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/product/{id}/basket/:
    post:
      operationId: basketVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: deleteBasketVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/product/{id}/favorite/:
    post:
      operationId: favoriteVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: deleteFavoriteVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - slug
    Type:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - slug
    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\u0433"
          maxLength: 200
        color:
          type: string
          description: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0446\u0432\u0435\
            \u0442 \u0442\u0435\u0433\u0430"
          maxLength: 7
        slug:
          type: string
          maxLength: 200
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - color
      - slug
    Size:
      type: object
      properties:
        length:
          type: integer
        width:
          type: integer
        height:
          type: integer
      required:
      - length
      - width
      - height
    VariationProduct:
      type: object
      properties:
        image:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              image:
                type: string
                format: binary
            required:
            - image
          readOnly: true
        price:
          type: integer
        sale:
          type: integer
        size:
          type: array
          items:
            type: integer
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
                description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\
                  \u0433"
                maxLength: 200
              color:
                type: string
                description: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0446\u0432\
                  \u0435\u0442 \u0442\u0435\u0433\u0430"
                maxLength: 7
              slug:
                type: string
                maxLength: 200
                pattern: ^[-a-zA-Z0-9_]+$
            required:
            - name
            - color
            - slug
          readOnly: true
        is_discount:
          type: string
          readOnly: true
        is_favorited:
          type: string
          readOnly: true
        is_in_basket:
          type: string
          readOnly: true
        product:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\
                \u0437\u0432\u0430\u043D\u0438\u0435 \u0442\u043E\u0432\u0430\u0440\
                \u0430"
              maxLength: 200
            text:
              type: string
              description: "\u041D\u0430\u043F\u0438\u0448\u0438\u0442\u0435 \u043E\
                \u043F\u0438\u0441\u0430\u043D\u0438\u0435 \u0442\u043E\u0432\u0430\
                \u0440\u0430"
            type:
              type: integer
              nullable: true
            category:
              type: array
              items:
                type: integer
          required:
          - name
          - category
          readOnly: true
        specification:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            article_number:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0430\u0440\
                \u0442\u0438\u043A\u0443\u043B \u0442\u043E\u0432\u0430\u0440\u0430"
              maxLength: 200
            model:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0438\
                \u043F \u0442\u043E\u0432\u0430\u0440\u0430"
              maxLength: 200
            materials:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043C\u0430\
                \u0442\u0435\u0440\u0438\u043B\u044B \u0442\u043E\u0432\u0430\u0440\
                \u0430"
              maxLength: 200
            manufacturer:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u041F\u0440\
                \u043E\u0438\u0437\u0432\u043E\u0434\u0438\u0442\u0435\u043B\u044F"
              maxLength: 200
            size:
              type: array
              items:
                type: integer
          required:
          - model
          - materials
          - manufacturer
          - size
          readOnly: true
      required:
      - price
      - sale
