openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/categories/:
    get:
      operationId: Список категорий
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
      tags:
      - api
  /api/categories/{id}/:
    get:
      operationId: получение категории
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальный идентификатор категории
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
      tags:
      - api
  /api/type/:
    get:
      operationId: Список Типов товаров
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Type'
          description: ''
      tags:
      - api
  /api/type/{id}/:
    get:
      operationId: получение типа
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: Уникальный идентификатор типа
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
      tags:
      - api
  /api/tags/:
    get:
      operationId: Cписок тегов(цветов)
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
          description: ''
      tags:
        - Теги
  /api/tags/{id}/:
    get:
      operationId: Получение тега
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный идентификатор этого Тега."
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
          description: ''
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Теги
  /api/size/:
    get:
      operationId: список размеров
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Size'
          description: ''
      tags:
      - api
  /api/size/{id}/:
    get:
      operationId: получение размера
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: уникальный идентификатор размера
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Size'
          description: ''
      tags:
      - api
  /api/product/:
    get:
      operationId: Список продуктов
      description: 'Страница доступна всем пользователям. Доступна фильтрация по цене, тегу(цвету),
      механизму, типу, добавлению в избраное, добавлению в корзину'
      parameters:
      - name: page
        required: false
        in: query
        description: номер страницы
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: Количество объектов на странице
        schema:
          type: integer
      - name: is_favorited
        required: false
        in: query
        description: Показывать только продукты, находящиеся в списке избранного.
        schema:
          type: integer
          enum: [ 0, 1 ]
      - name: is_in_basket
        required: false
        in: query
        description: Показывать только продукты, находящиеся в списке покупок.
        schema:
          type: integer
          enum: [ 0, 1 ]
      - name: type
        required: false
        in: query
        description: фильтрует продукты по указанным типам (по slug)
      - name: tags
        required: false
        in: query
        description: фильтрует продукты с указанными тегами (по slug)
      - name: min_price
        required: false
        in: query
        description: фильтрует минимальную цену
        schema:
          type: string
      - name: max_price
        required: false
        in: query
        description: фильтрует максимальную цену
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    post:
      operationId: createVariationProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
  /api/product/{id}/:
    get:
      operationId: retrieveVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    put:
      operationId: updateVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/product/{id}/basket/:
    post:
      operationId: basketVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: deleteBasketVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/product/{id}/favorite/:
    post:
      operationId: favoriteVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VariationProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/VariationProduct'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariationProduct'
          description: ''
      tags:
      - api
    delete:
      operationId: deleteFavoriteVariationProduct
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0421\u0442\u0430\u0442\
          \u044C\u044F."
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - slug
    Type:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - slug
    Tag:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\u0433"
          maxLength: 200
        color:
          type: string
          description: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0446\u0432\u0435\
            \u0442 \u0442\u0435\u0433\u0430"
          maxLength: 7
        slug:
          type: string
          maxLength: 200
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - name
      - color
      - slug
    Size:
      type: object
      properties:
        length:
          type: integer
        width:
          type: integer
        height:
          type: integer
      required:
      - length
      - width
      - height
    VariationProduct:
      type: object
      properties:
        image:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              image:
                type: string
                format: binary
            required:
            - image
          readOnly: true
        price:
          type: integer
        sale:
          type: integer
        size:
          type: array
          items:
            type: integer
        tags:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                readOnly: true
              name:
                type: string
                description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0435\
                  \u0433"
                maxLength: 200
              color:
                type: string
                description: "\u0423\u043A\u0430\u0436\u0438\u0442\u0435 \u0446\u0432\
                  \u0435\u0442 \u0442\u0435\u0433\u0430"
                maxLength: 7
              slug:
                type: string
                maxLength: 200
                pattern: ^[-a-zA-Z0-9_]+$
            required:
            - name
            - color
            - slug
          readOnly: true
        is_discount:
          type: string
          readOnly: true
        is_favorited:
          type: string
          readOnly: true
        is_in_basket:
          type: string
          readOnly: true
        product:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\
                \u0437\u0432\u0430\u043D\u0438\u0435 \u0442\u043E\u0432\u0430\u0440\
                \u0430"
              maxLength: 200
            text:
              type: string
              description: "\u041D\u0430\u043F\u0438\u0448\u0438\u0442\u0435 \u043E\
                \u043F\u0438\u0441\u0430\u043D\u0438\u0435 \u0442\u043E\u0432\u0430\
                \u0440\u0430"
            type:
              type: integer
              nullable: true
            category:
              type: array
              items:
                type: integer
          required:
          - name
          - category
          readOnly: true
        specification:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            article_number:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0430\u0440\
                \u0442\u0438\u043A\u0443\u043B \u0442\u043E\u0432\u0430\u0440\u0430"
              maxLength: 200
            mechanism:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0442\u0438\
                \u043F \u0442\u043E\u0432\u0430\u0440\u0430"
              maxLength: 200
            materials:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043C\u0430\
                \u0442\u0435\u0440\u0438\u043B\u044B \u0442\u043E\u0432\u0430\u0440\
                \u0430"
              maxLength: 200
            manufacturer:
              type: string
              description: "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u041F\u0440\
                \u043E\u0438\u0437\u0432\u043E\u0434\u0438\u0442\u0435\u043B\u044F"
              maxLength: 200
            size:
              type: array
              items:
                type: integer
          required:
          - mechanism
          - materials
          - manufacturer
          - size
          readOnly: true
      required:
      - price
      - sale
